sudo: required

services:
  - docker

language: go
go:
  - tip

env:
  global:
    - MYAPP=go-serve
    - MYEMAIL=anudeep.22cs@kct.ac.in
    - secure: GH_TOKEN

before_install:
  - sudo apt-get -qq update
  - mkdir -p ${GOPATH}/bin

install:
  - go install

script: echo "pass"

before_deploy:
  - mkdir -p build/{386,amd64}
  - GOOS=linux GOARCH=386 go build --ldflags "-X main.VERSION=${TRAVIS_TAG}" -o build/386/$MYAPP main.go
  - GOOS=linux GOARCH=amd64 go build --ldflags "-X main.VERSION=${TRAVIS_TAG}" -o build/amd64/$MYAPP main.go
  - curl -L https://raw.githubusercontent.com/mh-cbon/go-bin-deb/master/create-pkg.sh | GH=anudeep652/$MYAPP sh -xe

after_deploy:
  - curl -L https://raw.githubusercontent.com/mh-cbon/go-bin-deb/master/setup-repository.sh | GH=anudeep652/$MYAPP EMAIL=$MYEMAIL sh -xe

deploy:
  provider: releases
  api_key:
    secure: GH_TOKEN
  file_glob: true
  file:
    - $MYAPP-386.deb
    - $MYAPP-amd64.deb
  skip_cleanup: true
  on:
    tags: true
